export const jobs = [
  {
    slug: "jr-frontend-developer-2",
    title: "Jr. Frontend Developer",
    location: "Niketan, Gulshan 1, Dhaka 1212",
    type: "Full-time",
    level: "Entry to Mid-Level",
    about:
      "At Apptriangle Limited, we build innovative digital products that make a difference. Our team values creativity, clean code, and collaboration. We're looking for a passionate Junior Frontend Developer who loves turning designs into functional, responsive, and user-friendly web experiences.",
    responsibilities: [
      "Develop responsive and interactive user interfaces using HTML, CSS, and JavaScript (React, Next.js, or similar frameworks preferred).",
      "Work closely with designers and backend developers to implement new features and improve existing ones.",
      "Ensure cross-browser compatibility and performance optimization.",
      "Participate in code reviews and contribute to maintaining code quality.",
      "Stay updated with modern frontend technologies and best practices.",
    ],
    requirements: [
      "Bachelor's degree in Computer Science, IT, or a related field (or equivalent experience).",
      "0–2 years of experience in frontend web development.",
      "Good understanding of HTML5, CSS3, JavaScript, and responsive design.",
      "Familiarity with React.js, Next.js, or similar frameworks is a plus.",
      "Basic understanding of Git and version control.",
      "Eagerness to learn and grow in a fast-paced environment.",
    ],
    preferred: [
      "Experience with UI/UX tools like Figma or Adobe XD.",
      "Knowledge of RESTful APIs and JSON.",
      "Understanding of web performance optimization.",
    ],
    benefits: [
      "Friendly and supportive learning environment.",
      "Opportunities for professional growth and mentorship.",
      "Flexible working hours and a collaborative culture.",
      "Competitive salary and performance-based incentives.",
    ],
  },
  {
    slug: "react-developer",
    title: "React Developer",
    location: "Niketan, Gulshan 1, Dhaka 1212",
    type: "Full-time / Contract",
    level: "Mid to Senior Level",
    about:
      "Apptriangle Limited seeks a developer to create cutting-edge digital solutions that empower businesses and delight users.",
    responsibilities: [
      "Design responsive web and mobile interfaces",
      "Collaborate with cross-functional teams",
      "Create wireframes and prototypes",
      "Maintain design consistency",
      "Conduct user research",
      "Optimize for performance and accessibility",
    ],
    requirements: [
      "Bachelor's degree in Design, Computer Science, or related field",
      "2+ years of UI/UX and front-end experience",
      "Strong proficiency in HTML, CSS, and JavaScript with React or Next.js experience preferred",
      "Expertise with design tools like Figma or Adobe XD",
      "Portfolio demonstrating UI/UX work",
    ],
    preferred: [
      "Motion design experience",
      "Prototyping and animation tools",
      "Design systems knowledge",
      "Backend technology familiarity",
    ],
    benefits: [
      "Collaborative environment",
      "Meaningful work impacting thousands of users",
      "Flexible scheduling with remote options",
      "Competitive compensation",
      "Career advancement opportunities",
    ],
  },
  {
    slug: "next-js-developer",
    title: "Next Js Developer",
    location: "Remote",
    type: "Full-time",
    level: "Senior (5+ years)",
    about:
      "Apptriangle is a fast-growing IT solutions provider specializing in software development, automation, and digital transformation.",
    responsibilities: [
      "Design, develop, and maintain efficient, reusable, and reliable code",
      "Build APIs, backend systems, and integrations with third-party services",
      "Collaborate with front-end developers, DevOps, and product teams to deliver end-to-end solutions",
      "Optimize applications for maximum speed and scalability",
      "Conduct code reviews and mentor junior developers",
      "Troubleshoot, debug, and upgrade existing systems",
      "Contribute to architectural decisions and technology strategy",
    ],
    requirements: [
      "Bachelor's degree in Computer Science, Engineering, or related field",
      "5+ years of hands-on experience",
      "Strong understanding of RESTful API design and development",
      "Experience with relational databases (PostgreSQL, MySQL) and ORMs",
      "Familiarity with Docker, Git, and CI/CD pipelines",
      "Cloud platform knowledge (AWS, Azure, or GCP)",
      "Excellent problem-solving and communication skills",
      "Ability to work independently and collaboratively",
    ],
    preferred: [
      "Asynchronous frameworks experience (Celery, AsyncIO, RabbitMQ)",
      "Microservices architecture knowledge",
      "Frontend technologies familiarity (React, Vue.js)",
      "Testing frameworks experience (PyTest, UnitTest)",
    ],
    benefits: [
      "Competitive salary based on experience",
      "Flexible hours and remote work options",
      "Career development and learning opportunities",
      "Collaborative workplace culture",
    ],
  },
  {
    slug: "it-specialist",
    title: "IT Specialist",
    location: "Niketan, Gulshan 1, Dhaka 1212",
    type: "Full-time",
    level: "Entry to Mid-Level",
    about: null,
    responsibilities: [
      "Build responsive interfaces using HTML, CSS, and JavaScript with frameworks like React or Next.js",
      "Collaborate with designers and backend teams",
      "Ensure cross-browser compatibility",
      "Participate in code reviews",
      "Stay current with frontend technologies",
    ],
    requirements: [
      "Bachelor's degree in Computer Science, IT, or a related field",
      "0–2 years of frontend experience",
      "HTML5, CSS3, JavaScript, and responsive design principles",
      "Basic understanding of Git and version control",
    ],
    preferred: [
      "Experience with design tools like Figma",
      "Knowledge of RESTful APIs and JSON",
      "Web performance optimization skills",
    ],
    benefits: [
      "A friendly and supportive learning environment",
      "Professional development opportunities",
      "Flexible hours",
      "Competitive salary and performance-based incentives",
    ],
  },
  {
    slug: "sqa-developer",
    title: "SQA Developer",
    location: "Niketan, Gulshan 1, Dhaka 1212",
    type: "Full-time / Contract",
    level: "Mid to Senior Level",
    about: null,
    responsibilities: [
      "Design responsive interfaces",
      "Collaborate across teams",
      "Create wireframes and prototypes using design tools",
      "Maintain consistency across platforms",
      "Conduct user research and testing",
      "Optimize for performance and accessibility",
    ],
    requirements: [
      "Degree in Design or Computer Science (or equivalent)",
      "2+ years of UI/UX and front-end experience",
      "Proficiency in HTML, CSS, and JavaScript (React/Next.js preferred)",
      "Mastery of design tools like Figma or Adobe XD",
      "Strong portfolio",
      "Excellent communication and problem-solving skills",
    ],
    preferred: [
      "Experience with motion design",
      "Prototyping tools",
      "Design systems knowledge",
      "Backend technologies familiarity",
    ],
    benefits: [
      "Collaborative opportunities with creative teams",
      "Impact on user-facing products",
      "Flexible scheduling",
      "Remote-friendly arrangements",
      "Competitive compensation",
      "Career advancement prospects",
    ],
  },
  {
    slug: "devops-developer",
    title: "DevOps Developer",
    location: "Remote",
    type: "Full-time",
    level: "Senior (5+ years)",
    about:
      "Apptriangle is a fast-growing IT solutions provider specializing in software development, automation, and digital transformation.",
    responsibilities: [
      "Design, develop, and maintain efficient, reusable, and reliable code",
      "Build APIs, backend systems, and integrations with third-party services",
      "Collaborate with front-end developers, DevOps, and product teams to deliver end-to-end solutions",
      "Optimize applications for maximum speed and scalability",
      "Conduct code reviews and mentor junior developers",
      "Troubleshoot, debug, and upgrade existing systems",
      "Contribute to architectural decisions and technology strategy",
    ],
    requirements: [
      "Bachelor's degree in Computer Science, Engineering, or related field",
      "5+ years of hands-on experience",
      "Strong understanding of RESTful API design and development",
      "Experience with relational databases (PostgreSQL, MySQL) and ORMs",
      "Familiarity with Docker, Git, and CI/CD pipelines",
      "Good understanding of cloud platforms (AWS, Azure, or GCP)",
      "Excellent problem-solving and communication skills",
      "Ability to work independently and in a team environment",
    ],
    preferred: [
      "Experience with asynchronous frameworks (Celery, AsyncIO, RabbitMQ)",
      "Knowledge of microservices architecture",
      "Familiarity with frontend technologies (React, Vue.js)",
      "Experience with testing frameworks (PyTest, UnitTest)",
    ],
    benefits: [
      "Competitive salary based on experience",
      "Flexible working hours & remote work options",
      "Career growth opportunities and continuous learning",
      "Friendly, collaborative work culture",
    ],
  },
  {
    slug: "ui-ux-developer",
    title: "UI/UX Developer",
    location: "Niketan, Gulshan 1, Dhaka 1212",
    type: "Full-time / Contract",
    level: "Mid to Senior Level",
    about: null,
    responsibilities: [
      "Design responsive interfaces for web and mobile platforms",
      "Collaborate across teams",
      "Create wireframes and prototypes",
      "Ensure design consistency and usability across platforms",
      "Conduct user research to validate decisions",
    ],
    requirements: [
      "Bachelor's degree in design or related field",
      "2+ years of experience in UI/UX design and front-end development",
      "Proficiency in HTML, CSS, and JavaScript",
      "Expertise with design tools like Figma or Adobe XD",
      "Strong portfolio",
    ],
    preferred: [
      "Motion design experience",
      "Knowledge of design systems",
      "Familiarity with backend technologies",
    ],
    benefits: [
      "Flexible working hours and remote-friendly culture",
      "Competitive compensation",
      "Career development opportunities",
    ],
  },
  {
    slug: "sr-python-developer",
    title: "Sr. Python Developer",
    location: "Remote",
    type: "Full-time",
    level: "Senior (5+ years)",
    about:
      "Apptriangle is a fast-growing IT solutions provider specializing in software development, automation, and digital transformation.",
    responsibilities: [
      "Design, develop, and maintain efficient, reusable, and reliable Python code",
      "Build APIs, backend systems, and integrations with third-party services",
      "Collaborate with front-end developers, DevOps, and product teams to deliver end-to-end solutions",
      "Optimize applications for maximum speed and scalability",
      "Conduct code reviews and mentor junior developers",
      "Troubleshoot, debug, and upgrade existing systems",
      "Contribute to architectural decisions and technology strategy",
    ],
    requirements: [
      "Bachelor's degree in Computer Science, Engineering, or related field",
      "5+ years hands-on experience with Python (Django, Flask, or FastAPI)",
      "Strong understanding of RESTful API design and development",
      "Experience with relational databases (PostgreSQL, MySQL) and ORMs",
      "Familiarity with Docker, Git, and CI/CD pipelines",
      "Cloud platform knowledge (AWS, Azure, or GCP)",
      "Excellent problem-solving and communication skills",
      "Ability to work independently and collaboratively",
    ],
    preferred: [
      "Experience with asynchronous frameworks (Celery, AsyncIO, RabbitMQ)",
      "Knowledge of microservices architecture",
      "Familiarity with frontend technologies (React, Vue.js)",
      "Experience with testing frameworks (PyTest, UnitTest)",
    ],
    benefits: [
      "Competitive salary based on experience",
      "Flexible hours and remote work options",
      "Career development and learning opportunities",
      "Collaborative workplace culture",
    ],
  },
]

export type Job = (typeof jobs)[number]
